### PR TITLE
update application parts

### PR DESCRIPTION
**Pull request by alphaolomi**
Changes
- Changes to Bootstrap classes instead of style attributes 
- Movied dbconnect.php to ./configdb.php
- added layout/
- Cleaned up index.php
- moved style to ./assets/css/style.css
-

### CODE REVIEW

**Review by Abk47 — APPROVED** [review]
Awesome!

**Comment by alphaolomi** [comment]
Hey @Abk47 ,
You closed the pull request without merging, is it a mistake?
If not, I would recommend you check out how to merge PRs, https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request.

**Comment by Abk47** [comment]
Hey @alphaolomi , I thought I already approved and merged it already.

**Comment by Abk47** [comment]
Thank you for your valuable contribution @alphaolomi

**Review by alphaolomi — COMMENTED** [review]
Cool

**Pull request merged**
